/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package homeservice;

import static homeservice.signUp.stmt;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Hashtable;
import javax.print.DocFlavor;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MUKIT
 */
public class homePage extends javax.swing.JFrame {

    /**
     * Creates new form homePage
     */
    public homePage() {
        initComponents();
        logoutlabel.setText(null);
    }

    static Connection conn = null;
    static Statement stmt = null;

    public void createConnection() {
        try {
            //Connect conn = new Connect();
            conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "test", "test");
            stmt = conn.createStatement();
        } catch (SQLException e) {
            System.err.println("Error at create connection " + e);
        }
    }

    public void fillTable(JTable table, String Query) {
        try {
            createConnection();
            //To remove previously added rows
            try (ResultSet rs = stmt.executeQuery(Query)) {
                //To remove previously added rows
                while (table.getRowCount() > 0) {
                    ((DefaultTableModel) table.getModel()).removeRow(0);
                }
                int columns = rs.getMetaData().getColumnCount();
                while (rs.next()) {
                    Object[] row = new Object[columns];
                    for (int i = 1; i <= columns; i++) {
                        row[i - 1] = rs.getObject(i);
                    }
                    ((DefaultTableModel) table.getModel()).insertRow(rs.getRow() - 1, row);
                }
            }
            stmt.close();
            conn.close();
        } catch (SQLException e) {
            System.err.println("SQL error at fill table\n" + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        logoutlabel = new javax.swing.JLabel();
        loginBtn = new javax.swing.JLabel();
        newUser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        trending = new javax.swing.JButton();
        basicSerButton = new javax.swing.JButton();
        homeAppButton = new javax.swing.JButton();
        ItButton = new javax.swing.JButton();
        checkout = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Trending = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        basicServices = new javax.swing.JPanel();
        midblur1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        homeApp = new javax.swing.JPanel();
        midBlur = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        ITServices = new javax.swing.JPanel();
        midBlur2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        computer = new javax.swing.JCheckBox();
        printer = new javax.swing.JCheckBox();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        amount = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        noOfService = new javax.swing.JLabel();
        router = new javax.swing.JCheckBox();
        cellPhone = new javax.swing.JCheckBox();
        CheckOut = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        amount1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        noOfService1 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        confirmOrderBtn = new javax.swing.JButton();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        jPanel1.setPreferredSize(new java.awt.Dimension(700, 100));
        jPanel1.setLayout(null);

        logoutlabel.setText("LOG OUT");
        logoutlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutlabelMouseClicked(evt);
            }
        });
        jPanel1.add(logoutlabel);
        logoutlabel.setBounds(20, 70, 60, 16);

        loginBtn.setForeground(new java.awt.Color(255, 255, 102));
        loginBtn.setText("LOGIN");
        loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBtnMouseExited(evt);
            }
        });
        jPanel1.add(loginBtn);
        loginBtn.setBounds(20, 10, 110, 16);

        newUser.setForeground(new java.awt.Color(255, 255, 255));
        newUser.setText("New User ? ");
        newUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newUserMouseExited(evt);
            }
        });
        jPanel1.add(newUser);
        newUser.setBounds(20, 30, 70, 16);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homeservice/homeTopimg.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 100);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        trending.setFont(new java.awt.Font("Juice ITC", 1, 18)); // NOI18N
        trending.setText("Trending");
        trending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trendingActionPerformed(evt);
            }
        });

        basicSerButton.setText("Basic Services");
        basicSerButton.setToolTipText("");
        basicSerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basicSerButtonActionPerformed(evt);
            }
        });

        homeAppButton.setText("Home Appliances");
        homeAppButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeAppButtonActionPerformed(evt);
            }
        });

        ItButton.setText("IT Services");
        ItButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItButtonActionPerformed(evt);
            }
        });

        checkout.setText("CheckOut");
        checkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homeAppButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(basicSerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ItButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(trending, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(checkout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(trending, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(basicSerButton)
                .addGap(18, 18, 18)
                .addComponent(homeAppButton)
                .addGap(18, 18, 18)
                .addComponent(ItButton)
                .addGap(18, 18, 18)
                .addComponent(checkout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setLayout(new java.awt.CardLayout());

        Trending.setBackground(new java.awt.Color(153, 153, 153));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homeservice/trending.jpg"))); // NOI18N

        javax.swing.GroupLayout TrendingLayout = new javax.swing.GroupLayout(Trending);
        Trending.setLayout(TrendingLayout);
        TrendingLayout.setHorizontalGroup(
            TrendingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        TrendingLayout.setVerticalGroup(
            TrendingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.add(Trending, "card2");

        basicServices.setBackground(new java.awt.Color(153, 153, 153));
        basicServices.setLayout(null);

        midblur1.setBackground(new Color(0,0, 0, 170));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homeservice/gasStove.jpg"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homeservice/home-electricity-620x330.jpg"))); // NOI18N
        jLabel3.setText("jLabel2");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homeservice/key and lock.jpg"))); // NOI18N
        jLabel4.setText("jLabel2");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homeservice/plumbing-supplies.jpg"))); // NOI18N

        jButton5.setText("Gas Stove");

        jButton6.setText("Plumbing");

        jButton7.setText("Key & Lock");

        jButton8.setText("Electricity");

        javax.swing.GroupLayout midblur1Layout = new javax.swing.GroupLayout(midblur1);
        midblur1.setLayout(midblur1Layout);
        midblur1Layout.setHorizontalGroup(
            midblur1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(midblur1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(midblur1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addGroup(midblur1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(midblur1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(midblur1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        midblur1Layout.setVerticalGroup(
            midblur1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(midblur1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(midblur1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(midblur1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(midblur1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton8)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        basicServices.add(midblur1);
        midblur1.setBounds(40, 50, 450, 200);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homeservice/homeBasic.jpg"))); // NOI18N
        basicServices.add(jLabel5);
        jLabel5.setBounds(0, 0, 524, 294);

        jPanel3.add(basicServices, "card2");

        homeApp.setBackground(new java.awt.Color(0, 153, 204));
        homeApp.setLayout(null);

        midBlur.setBackground(new Color(0,0, 0, 170));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homeservice/fridge.jpg"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homeservice/ac.jpg"))); // NOI18N
        jLabel9.setText("jLabel8");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homeservice/washing maching.jpg"))); // NOI18N
        jLabel10.setText("jLabel8");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homeservice/tv.jpg"))); // NOI18N
        jLabel11.setText("jLabel8");

        jButton1.setText("Refrigeretor");

        jButton2.setText("Ac");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("TV");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Washing Machine");
        jButton4.setToolTipText("");

        javax.swing.GroupLayout midBlurLayout = new javax.swing.GroupLayout(midBlur);
        midBlur.setLayout(midBlurLayout);
        midBlurLayout.setHorizontalGroup(
            midBlurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, midBlurLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(midBlurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(midBlurLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(midBlurLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(midBlurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addGap(38, 38, 38))
        );
        midBlurLayout.setVerticalGroup(
            midBlurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(midBlurLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(midBlurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(midBlurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(midBlurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        homeApp.add(midBlur);
        midBlur.setBounds(30, 30, 460, 190);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homeservice/homeAppliance.jpg"))); // NOI18N
        homeApp.add(jLabel7);
        jLabel7.setBounds(0, 0, 524, 294);

        jPanel3.add(homeApp, "card2");

        ITServices.setBackground(new java.awt.Color(153, 153, 255));
        ITServices.setLayout(null);

        midBlur2.setBackground(new Color(0,0, 0, 170));
        midBlur2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homeservice/computer.jpg"))); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homeservice/router.jpg"))); // NOI18N
        jLabel14.setText("jLabel13");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homeservice/printer.jpg"))); // NOI18N
        jLabel15.setText("jLabel13");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homeservice/mobilerepair.jpg"))); // NOI18N
        jLabel16.setText("jLabel13");

        computer.setText("Computer");
        computer.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                computerStateChanged(evt);
            }
        });
        computer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computerActionPerformed(evt);
            }
        });

        printer.setText("Printer");
        printer.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                printerStateChanged(evt);
            }
        });
        printer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printerActionPerformed(evt);
            }
        });

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("No. of services: ");

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Toatal Amount:");

        amount.setBackground(new java.awt.Color(255, 255, 255));
        amount.setForeground(new java.awt.Color(255, 255, 255));
        amount.setText("                         ");

        noOfService.setForeground(new java.awt.Color(255, 255, 255));
        noOfService.setText("                         ");

        router.setText("Router");
        router.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routerActionPerformed(evt);
            }
        });

        cellPhone.setText("cellPhone");
        cellPhone.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cellPhoneStateChanged(evt);
            }
        });
        cellPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cellPhoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout midBlur2Layout = new javax.swing.GroupLayout(midBlur2);
        midBlur2.setLayout(midBlur2Layout);
        midBlur2Layout.setHorizontalGroup(
            midBlur2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, midBlur2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(midBlur2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addGroup(midBlur2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(computer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(midBlur2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(midBlur2Layout.createSequentialGroup()
                        .addComponent(noOfService, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21))
                    .addGroup(midBlur2Layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addGroup(midBlur2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(router, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(midBlur2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(printer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(midBlur2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, midBlur2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(midBlur2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(midBlur2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cellPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18))
        );
        midBlur2Layout.setVerticalGroup(
            midBlur2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(midBlur2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(midBlur2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(midBlur2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(midBlur2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(computer)
                        .addComponent(router))
                    .addGroup(midBlur2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(printer)
                        .addComponent(cellPhone)))
                .addGap(18, 18, 18)
                .addGroup(midBlur2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(amount)
                    .addComponent(jLabel23)
                    .addComponent(noOfService))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        ITServices.add(midBlur2);
        midBlur2.setBounds(30, 20, 460, 220);

        jPanel3.add(ITServices, "card2");

        CheckOut.setForeground(new java.awt.Color(0, 0, 0));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Service", "Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        amount1.setBackground(new java.awt.Color(255, 255, 255));
        amount1.setForeground(new java.awt.Color(0, 0, 0));
        amount1.setText("                         ");

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("No. of services: ");

        noOfService1.setForeground(new java.awt.Color(0, 0, 0));
        noOfService1.setText("                         ");

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Toatal Amount:");

        confirmOrderBtn.setText("Confirm Order");
        confirmOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmOrderBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CheckOutLayout = new javax.swing.GroupLayout(CheckOut);
        CheckOut.setLayout(CheckOutLayout);
        CheckOutLayout.setHorizontalGroup(
            CheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CheckOutLayout.createSequentialGroup()
                .addGroup(CheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CheckOutLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CheckOutLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(CheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(confirmOrderBtn)
                            .addGroup(CheckOutLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(noOfService1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(jLabel24)))
                        .addGap(31, 31, 31)
                        .addComponent(amount1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        CheckOutLayout.setVerticalGroup(
            CheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CheckOutLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(CheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel24)
                    .addComponent(amount1)
                    .addComponent(noOfService1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(confirmOrderBtn)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel3.add(CheckOut, "card6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void basicSerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basicSerButtonActionPerformed
        // TODO add your handling code here:
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(basicServices);
        jPanel3.repaint();
        jPanel3.revalidate();


    }//GEN-LAST:event_basicSerButtonActionPerformed

    private void homeAppButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeAppButtonActionPerformed
        // TODO add your handling code here:
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(homeApp);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_homeAppButtonActionPerformed

    private void trendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trendingActionPerformed
        // TODO add your handling code here:
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(Trending);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_trendingActionPerformed

    private void ItButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItButtonActionPerformed
        // TODO add your handling code here:
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(ITServices);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_ItButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    public Hashtable<String, String> login(JFrame frame) {
        Hashtable<String, String> logininformation = new Hashtable<String, String>();

        JPanel panel = new JPanel(new BorderLayout(5, 5));

        JPanel label = new JPanel(new GridLayout(0, 1, 2, 2));
        label.add(new JLabel("User ID", SwingConstants.RIGHT));
        label.add(new JLabel("Password", SwingConstants.RIGHT));
        panel.add(label, BorderLayout.WEST);

        JPanel controls = new JPanel(new GridLayout(0, 1, 2, 2));
        JTextField username = new JTextField();
        controls.add(username);
        JPasswordField password = new JPasswordField();
        controls.add(password);
        panel.add(controls, BorderLayout.CENTER);

        JOptionPane.showMessageDialog(frame, panel, "login", JOptionPane.QUESTION_MESSAGE);

        logininformation.put("user", username.getText());
        logininformation.put("pass", new String(password.getPassword()));
        return logininformation;
    }
    private void loginBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseClicked

        if (login == false) {
            setVisible(true);
            while (true) {

                logininformation = login(this);
                String user = logininformation.get("user");
                String pass = logininformation.get("pass");

                if (pass.equals("admin") == true && user.equals("admin") == true) {
                    setVisible(false);
                    new adminPanel().setVisible(true);
                    login = true;
                    break;
                } else if (pass.equals("") == true && user.equals("") == true) {
                    setVisible(false);
                    new adminPanel().setVisible(true);
                    login = true;
                    break;
                } else if (pass.equals(user) == true && pass.equals("") == false) {
                    loginBtn.setForeground(Color.WHITE);
                    loginBtn.setText("HI, " + user);
                    newUser.setText("");
                    login = true;
                    logoutlabel.setText("LOG OUT");
                    logoutlabel.setForeground(Color.WHITE);
                    setVisible(true);
                    break;
                } else {
                    JOptionPane.showMessageDialog(rootPane, "ID- Password Didn't match");
                }

            }
        }


    }//GEN-LAST:event_loginBtnMouseClicked

    private void loginBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseEntered
        // TODO add your handling code here:
        if (login == false) {
            loginBtn.setForeground(Color.green);
        }
    }//GEN-LAST:event_loginBtnMouseEntered

    private void loginBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseExited
        // TODO add your handling code here:
        if (login == false) {
            loginBtn.setForeground(Color.yellow);
        }

    }//GEN-LAST:event_loginBtnMouseExited

    private void newUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newUserMouseClicked
        // TODO add your handling code here:
        if (login == false) {
            setVisible(false);
            new signUp().setVisible(true);
        }
    }//GEN-LAST:event_newUserMouseClicked

    private void newUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newUserMouseEntered
        // TODO add your handling code here:
        if (login == false) {
            newUser.setForeground(Color.BLUE);
        }
    }//GEN-LAST:event_newUserMouseEntered

    private void computerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computerActionPerformed
        try {
            createConnection();

            if (computer.isSelected()) {
                ResultSet rs = stmt.executeQuery("Select SERVICE_CHARGE from SERVICES_CHILD where child_name= 'Computer'");
                int amt = 0;
                if (rs.next()) {
                    amt = rs.getInt("service_charge");
                }
                stmt.executeQuery("insert into temp values('Computer'," + amt + ")");
            } else {
                stmt.executeQuery("Delete from temp where service = 'Computer'");
            }

            ResultSet rs = stmt.executeQuery("Select count(amount) as cnt from temp");
            if (rs.next()) {
                noOfService.setText(String.valueOf(rs.getInt("cnt")));
            }

            rs = stmt.executeQuery("Select sum(amount) as total from temp");
            if (rs.next()) {
                amount.setText(String.valueOf(rs.getInt("total")));
            }
            stmt.close();
            conn.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, e + " computer state changed");
        }

    }//GEN-LAST:event_computerActionPerformed

    private void printerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printerActionPerformed
        // TODO add your handling code here:
        try {
            createConnection();

            if (printer.isSelected()) {
                ResultSet rs = stmt.executeQuery("Select SERVICE_CHARGE from SERVICES_CHILD where child_name= 'Printer'");
                int amt = 0;
                if (rs.next()) {
                    amt = rs.getInt("service_charge");
                }
                stmt.executeQuery("insert into temp values('Printer'," + amt + ")");
            } else {
                stmt.executeQuery("Delete from temp where service = 'Printer'");
            }

            ResultSet rs = stmt.executeQuery("Select count(amount) as cnt from temp");
            if (rs.next()) {
                noOfService.setText(String.valueOf(rs.getInt("cnt")));
            }

            rs = stmt.executeQuery("Select sum(amount) as total from temp");
            if (rs.next()) {
                amount.setText(String.valueOf(rs.getInt("total")));
            }
            stmt.close();
            conn.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, e + " Printer state changed");
        }
    }//GEN-LAST:event_printerActionPerformed

    private void computerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_computerStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_computerStateChanged

    private void printerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_printerStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_printerStateChanged

    private void checkoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutActionPerformed
        // TODO add your handling code here:
        if (login == true) {
            jPanel3.removeAll();
            jPanel3.repaint();
            jPanel3.revalidate();

            jPanel3.add(CheckOut);
            jPanel3.repaint();
            jPanel3.revalidate();

            try {
                createConnection();
                ResultSet rs = stmt.executeQuery("Select count(amount) as cnt from temp");
                if (rs.next()) {
                    noOfService1.setText(String.valueOf(rs.getInt("cnt")));
                }

                rs = stmt.executeQuery("Select sum(amount) as total from temp");
                if (rs.next()) {
                    amount1.setText(String.valueOf(rs.getInt("total")));
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(rootPane, e + "check out ");

            }

            fillTable(jTable1, "select * from temp");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Please Login/Sign up first", null, JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_checkoutActionPerformed

    private void routerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routerActionPerformed
        // TODO add your handling code here:
        try {
            createConnection();

            if (router.isSelected()) {
                ResultSet rs = stmt.executeQuery("Select SERVICE_CHARGE from SERVICES_CHILD where child_name= 'Router'");
                int amt = 0;
                if (rs.next()) {
                    amt = rs.getInt("service_charge");
                }
                stmt.executeQuery("insert into temp values('Router'," + amt + ")");
            } else {
                stmt.executeQuery("Delete from temp where service = 'Router'");
            }

            ResultSet rs = stmt.executeQuery("Select count(amount) as cnt from temp");
            if (rs.next()) {
                noOfService.setText(String.valueOf(rs.getInt("cnt")));
            }

            rs = stmt.executeQuery("Select sum(amount) as total from temp");
            if (rs.next()) {
                amount.setText(String.valueOf(rs.getInt("total")));
            }
            stmt.close();
            conn.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, e + " computer state changed");
        }
    }//GEN-LAST:event_routerActionPerformed

    private void cellPhoneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cellPhoneStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cellPhoneStateChanged

    private void cellPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cellPhoneActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        try {
            createConnection();

            if (cellPhone.isSelected()) {
                ResultSet rs = stmt.executeQuery("Select SERVICE_CHARGE from SERVICES_CHILD where child_name= 'CellPhone'");
                int amt = 0;
                if (rs.next()) {
                    amt = rs.getInt("service_charge");
                }
                stmt.executeQuery("insert into temp values('CellPhone'," + amt + ")");
            } else {
                stmt.executeQuery("Delete from temp where service = 'CellPhone'");
            }

            ResultSet rs = stmt.executeQuery("Select count(amount) as cnt from temp");
            if (rs.next()) {
                noOfService.setText(String.valueOf(rs.getInt("cnt")));
            }

            rs = stmt.executeQuery("Select sum(amount) as total from temp");
            if (rs.next()) {
                amount.setText(String.valueOf(rs.getInt("total")));
            }
            stmt.close();
            conn.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, e + " CellPhone state changed");
        }
    }//GEN-LAST:event_cellPhoneActionPerformed

    private void confirmOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmOrderBtnActionPerformed
        try {
            createConnection();
            ResultSet rs = stmt.executeQuery("Select count(amount) as cnt from temp");
            if (rs.next()) {
                noOfService1.setText(String.valueOf(rs.getInt("cnt")));
            }

            rs = stmt.executeQuery("Select sum(amount) as total from temp");
            if (rs.next()) {
                amount1.setText(String.valueOf(rs.getInt("total")));
            }

            JOptionPane.showMessageDialog(rootPane, "Order Confirmed", "Confirmation", JOptionPane.PLAIN_MESSAGE);

            stmt.close();
            conn.close();
            createConnection();
            Statement stmt2 = conn.createStatement();
            rs = stmt2.executeQuery("Select * from temp");
            while (rs.next()) {
                stmt.executeQuery("insert into TRANSACTION (AMOUNT,CUS_ID,STATUS,SERVICE) values(" + rs.getInt("AMOUNT") + ",'1',"
                        + "'No','" + rs.getString("service") + "')");
            }
            stmt.executeQuery("delete from temp");

            stmt.close();
            conn.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, e + " confirm state changed");
        }

    }//GEN-LAST:event_confirmOrderBtnActionPerformed

    private void newUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newUserMouseExited
        // TODO add your handling code here:
        if (login == false) {
            newUser.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_newUserMouseExited

    private void logoutlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutlabelMouseClicked
//       try {
//            createConnection();
//            stmt.executeQuery("delete from temp");
//            stmt.close();
//            conn.close();
//        } catch (SQLException e) {
//            JOptionPane.showMessageDialog(rootPane, e + " confirm state changed");
//        }
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(Trending);
        jPanel3.repaint();
        jPanel3.revalidate();
        
        logoutlabel.setText(null);
        login = false;
        loginBtn.setText("Login");
        newUser.setText("Sign Up");
    }//GEN-LAST:event_logoutlabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homePage().setVisible(true);
            }
        });
    }
    Hashtable<String, String> logininformation = null;
    private boolean login = false;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CheckOut;
    private javax.swing.JPanel ITServices;
    private javax.swing.JButton ItButton;
    private javax.swing.JPanel Trending;
    private javax.swing.JLabel amount;
    private javax.swing.JLabel amount1;
    private javax.swing.JButton basicSerButton;
    private javax.swing.JPanel basicServices;
    private javax.swing.JCheckBox cellPhone;
    private javax.swing.JButton checkout;
    private javax.swing.JCheckBox computer;
    private javax.swing.JButton confirmOrderBtn;
    private javax.swing.JPanel homeApp;
    private javax.swing.JButton homeAppButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel loginBtn;
    private javax.swing.JLabel logoutlabel;
    private javax.swing.JPanel midBlur;
    private javax.swing.JPanel midBlur2;
    private javax.swing.JPanel midblur1;
    private javax.swing.JLabel newUser;
    private javax.swing.JLabel noOfService;
    private javax.swing.JLabel noOfService1;
    private javax.swing.JCheckBox printer;
    private javax.swing.JCheckBox router;
    private javax.swing.JButton trending;
    // End of variables declaration//GEN-END:variables
}
